name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Check for package-lock.json
      - name: Check for package-lock.json
        id: check_lockfile
        run: |
          if [ -f package-lock.json ]; then
            echo "Lockfile exists."
            echo "lockfile=true" >> $GITHUB_ENV
          else
            echo "No lockfile found."
            echo "lockfile=false" >> $GITHUB_ENV
          fi

      # Install dependencies
      - name: Install Dependencies
        run: |
          if [ "$lockfile" = "true" ]; then
            npm ci
          else
            npm install
          fi

      # Run Tests
      - name: Run Tests
        run: npm test

      # Build the Project
      - name: Build the Project
        run: npm run build

